# Basic Switch Configuration Template
# This template provides a basic configuration for Cisco switches

template_name: "Basic Switch Configuration"
template_description: "Standard configuration template for Cisco switches"
template_type: "network"
version: "1.0"

parameters:
  - name: "hostname"
    type: "string"
    description: "Hostname for the switch"
    required: true
    default: "SW-001"
  
  - name: "management_vlan"
    type: "integer"
    description: "Management VLAN ID"
    required: true
    default: 99
  
  - name: "management_ip"
    type: "string"
    description: "Management IP address"
    required: true
    default: "192.168.1.100"
  
  - name: "management_mask"
    type: "string"
    description: "Management subnet mask"
    required: true
    default: "255.255.255.0"
  
  - name: "default_gateway"
    type: "string"
    description: "Default gateway IP"
    required: true
    default: "192.168.1.1"

configuration:
  - "hostname {{ hostname }}"
  - "!"
  - "! Management VLAN Configuration"
  - "vlan {{ management_vlan }}"
  - "  name Management"
  - "!"
  - "! Management Interface Configuration"
  - "interface vlan {{ management_vlan }}"
  - "  ip address {{ management_ip }} {{ management_mask }}"
  - "  no shutdown"
  - "!"
  - "! Default Gateway"
  - "ip default-gateway {{ default_gateway }}"
  - "!"
  - "! Basic Security Configuration"
  - "enable secret cisco"
  - "service password-encryption"
  - "!"
  - "! SSH Configuration"
  - "ip domain-name example.com"
  - "crypto key generate rsa modulus 2048"
  - "ip ssh version 2"
  - "line vty 0 15"
  - "  transport input ssh"
  - "  login local"
  - "!"
  - "! SNMP Configuration"
  - "snmp-server community public RO"
  - "snmp-server community private RW"
  - "!"
  - "! Logging Configuration"
  - "logging host {{ management_ip }}"
  - "logging trap informational"
  - "!"
  - "! NTP Configuration"
  - "ntp server {{ default_gateway }}"
  - "!"
  - "! Save Configuration"
  - "write memory"
