version: '3.8'

services:
  catalyst-templates-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: catalyst-center-templates-dev
    ports:
      - "8080:5000"
    volumes:
      # Mount source code for hot reloading
      - .:/app
      # Mount template directories
      - ./templates:/app/templates
      - ./data:/app/data
      - ./logs:/app/logs
      - ./output:/app/output
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
    restart: unless-stopped
    command: ["python", "app.py"]
